version: '3.9'

services:
  sales_db:
    image: mysql
    environment:
      MYSQL_DATABASE: mary_store
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - sales_data:/var/lib/mysqlw
    ports:
      - "3306:3306"
    networks:
      - bd
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 3s
      retries: 10

  my_app:
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - sales_db
    environment:
      IS_DOCKER: 'yes'
    volumes:
      - .:/app
    networks:
      - bd

volumes:
  sales_data:
networks:
  bd:
    driver: bridge
